### ISSUE TITLE
Would you mind sharing the paper?

### ISSUE THREAD

**Issue by aboutx** [snucml/LargeLossMatters#1]
Congratulations on such an excellent job!  Would you mind sharing the paper?
Thanks very much!
20120346@bjtu.edu.cn

**Comment by youngwk** [comment]
Hello, thanks for your interest in our work.
We are planning to upload our paper to arXiv this week. 
After it is uploaded, we will let you know.

**Comment by youngwk** [comment]
Hello, our paper is uploaded in arXiv.
You can check it out below.
https://arxiv.org/abs/2206.03740

**Comment by aboutx** [comment]
> Hello, our paper is uploaded in arXiv. You can check it out below. https://arxiv.org/abs/2206.03740

Great! Thank you again!
