### ISSUE TITLE
OpenImages dataset download

### ISSUE THREAD

**Issue by jameslahm** [snucml/LargeLossMatters#5]
Hi, Thank you for your great work!
I try to download the rest of training images via its URL using https://github.com/snucml/LargeLossMatters/blob/main/data/openimages/downloader.py, but all the images are NOT FOUND. I generate images id file like these.
```
train/000007e5752f8f1c
train/000056beaaea0225
train/000059e96d42da48
```
Is there something wrong? Thanks very much!

**Comment by youngwk** [comment]
Thank you for your interest. 
When I was first downloading the dataset last year, I also faced the same issue.
It seems that some images are not accessible (or maybe lost) on the server.
The actual number of training image is 3.7M, but I got only 3.4M images.

**Comment by jameslahm** [comment]
Thanks for the reply!
And I cannot get any images by downloading the dataset using `download.py`. It seems that all the images are not found now. Would you mind sharing the openimages dataset you use in a way that is convenient for you? Thanks a lot!

**Comment by youngwk** [comment]
I'm afraid that sharing the dataset directly may be difficult due to its huge file size. 
Instead, I have just modified the instruction and checked that downloading training images performs well when following modified instructions. 
Would you please check it? 
(Please conduct after removing ```images_train``` folder.)

**Comment by jameslahm** [comment]
Thanks for the reply!
In the new way, I can only get 1.7M images like before.

**Comment by youngwk** [comment]
Did you pull the new commit and re-execute ```generate_imageid_list.py``` and ```download.py``` with the folder ```images_train``` empty?

When I executed ```download.py``` today, the following message appeared in the command, and the folder was filled with images.
Downloading images:   0%|                                                                     | 4015/3759196 [02:22<22:01:51, 47.35it/s]

Could you share what message you get when you follow the instruction?
