### ISSUE TITLE
how to determine delta_rel

### ISSUE THREAD

**Issue by jerrywyn** [snucml/LargeLossMatters#8]
It looks like there is a correlation between the hyperparameter delta_rel and the noise of the dataset (the number of missing labels in the dataset). Can I ask how you determined delta_rel? Especially on a large dataset like OpenImages V3?

**Comment by youngwk** [comment]
Sorry for the late response. We determined delta_rel on a search space of {0.1, 0.2, 0.3, 0.4, 0.5} via grid search. We set the same search space for four artificially created partial label datasets (Sec 4.1). These are also described in Supplementary. In the case of OpenImages V3, its number of categories has a different order of magnitude. We thus adjusted the search space accordingly.
